name: Node.js

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test

  deploy:
    needs: build
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [12.x]
    name: Node.js
    steps:
    - name: Install dependencies
      run: npm ci
    - name: Deploy
      run: npm run deploy --if-present

  cd:
    needs: deploy
    runs-on: windows-latest
    steps:
    - name: Do continuous delivery
      run: |
        git remote add upstream https://github.com/idk
        git push upstream main
